/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/types/worker-configuration.d.ts` (hash: a5ae58dcdd7f5eaf433ea7ceb3139814)
interface __BaseEnv_Env {
	GATEWAY_CONTAINER: DurableObjectNamespace<import("../index").GatewayContainer>;
	FOREST_API: Fetcher /* forest-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../index");
		durableNamespaces: "GatewayContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
